apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dmsx-api
  namespace: dmsx
  labels:
    app.kubernetes.io/name: dmsx-api
    app.kubernetes.io/part-of: dmsx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dmsx-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dmsx-device-gw
  namespace: dmsx
  labels:
    app.kubernetes.io/name: dmsx-device-gw
    app.kubernetes.io/part-of: dmsx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dmsx-device-gw
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

